# Generated by Django 5.1.3 on 2024-11-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0006_alter_stockquote_raw_timestamp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
    ]
